package game.items;

import edu.monash.fit2099.engine.actors.Actor;
import edu.monash.fit2099.engine.items.Item;
import edu.monash.fit2099.engine.positions.Ground;
import edu.monash.fit2099.engine.positions.Location;
import edu.monash.fit2099.engine.statistics.BaseStatistic;
import game.ItemStatistics;
import game.capabilities.FireStackable;
import game.capabilities.UpdateNotifier;
import game.grounds.Fire;

import java.util.Random;

/**
 * A portable light source that presents a fire hazard.
 * The lantern has a chance to leak oil every turn, which ignites the
 * ground beneath the carrier.
 *
 * @author Jewell Gomes
 */
public class Lantern extends Item implements UpdateNotifier {
    private static final int INITIAL_OIL = 10;
    private static final double LEAK_CHANCE = 0.05;
    private int oil = INITIAL_OIL;
    private final Random random = new Random();
    private String latestNote = null;

    /**
     * Constructor for the Lantern.
     * Assigns a weight of seven unit and makes the item portable.
     */
    public Lantern() {
        super("Lantern", '&');
        this.addNewStatistic(ItemStatistics.WEIGHT, new BaseStatistic(7));
        this.makePortable();
    }

    /**
     * Handles the passage of time for the lantern.
     * Calculates the probability of an oil leak and creates fire on
     * the current tile if a leak occurs.
     * @param currentLocation The map location of the lantern.
     * @param actor           The actor carrying the lantern.
     */
    @Override
    public void tick(Location currentLocation, Actor actor) {
        if (actor != null && oil > 0 && random.nextDouble() < LEAK_CHANCE) {
            oil--;
            this.latestNote = "The lantern carried by " + actor + " leaks and ignites the ground!";
            FireStackable existingFire = currentLocation.getGroundAs(FireStackable.class);

            if (existingFire != null) {
                // If it's already fire, just add a stack damage increases
                existingFire.addStack();
            } else {
                // If it's not fire, create the first stack
                Ground groundBeforeFire = currentLocation.getGround();
                currentLocation.setGround(new Fire(groundBeforeFire));
            }
        }
    }

    /**
     * Retrieves the most recent event message generated by the lantern.
     * @return A notification string describing a leak, or null if no event occurred.
     */
    @Override
    public String updateMessage() {
        String msg = this.latestNote;
        this.latestNote = null;
        return msg;
    }

    /**
     * Returns a string representation of the lantern including its fuel level.
     * @return The item name and remaining oil units.
     */
    @Override
    public String toString() {
        return super.toString() + " (Oil: " + oil + ")";
    }
}
