package game.items;

import edu.monash.fit2099.engine.actors.Actor;
import edu.monash.fit2099.engine.items.Item;
import edu.monash.fit2099.engine.positions.Exit;
import edu.monash.fit2099.engine.positions.GameMap;
import edu.monash.fit2099.engine.positions.Ground;
import edu.monash.fit2099.engine.positions.Location;
import edu.monash.fit2099.engine.statistics.BaseStatistic;
import game.capabilities.BurningStatus;
import game.capabilities.CreditHolder;
import game.capabilities.FireStackable;
import game.capabilities.Infectable;
import game.capabilities.InfectionStatus;
import game.capabilities.Sellable;
import game.capabilities.UpdateNotifier;
import game.enums.ItemStatistics;
import game.grounds.Fire;

import java.util.Random;

/**
 * A portable light source that presents a fire hazard.
 * The lantern has a chance to leak oil every turn, which ignites the
 * ground beneath the carrier. It can also be sold to the Supercomputer
 * and affected by infection.
 *
 * @author Jewell Gomes
 * @author Chathya Attanayake
 * @author Suchir
 * @version 1.0
 */
public class Lantern extends Item implements UpdateNotifier, Sellable, Infectable {
    private static final int INITIAL_OIL = 10;
    private static final double LEAK_CHANCE = 0.05;

    private static final int PRICE_PER_OIL = 5;
    private static final int BURN_CHANCE = 50;
    private static final int FIRE_CHANCE = 25;
    private static final int BURN_DURATION = 3;

    private int oil = INITIAL_OIL;
    private final Random random = new Random();
    private String latestNote = null;

    /**
     * Constructor for the Lantern.
     * Assigns a weight of seven units and makes the item portable.
     */
    public Lantern() {
        super("Lantern", '&');
        this.addNewStatistic(ItemStatistics.WEIGHT, new BaseStatistic(7));
        this.makePortable();
    }

    /**
     * Handles the passage of time for the lantern.
     * Calculates the probability of an oil leak and creates fire on
     * the current tile if a leak occurs.
     *
     * @param currentLocation the map location of the lantern
     * @param actor the actor carrying the lantern
     */
    @Override
    public void tick(Location currentLocation, Actor actor) {
        if (actor != null && oil > 0 && random.nextDouble() < LEAK_CHANCE) {
            oil--;
            this.latestNote = "The lantern carried by " + actor + " leaks and ignites the ground!";
            FireStackable existingFire = currentLocation.getGroundAs(FireStackable.class);

            if (existingFire != null) {
                existingFire.addStack();
            } else {
                Ground groundBeforeFire = currentLocation.getGround();
                currentLocation.setGround(new Fire(groundBeforeFire));
            }
        }
    }

    /**
     * Retrieves the most recent event message generated by the lantern.
     *
     * @return a notification string describing a leak, or null if no event occurred
     */
    @Override
    public String updateMessage() {
        String msg = this.latestNote;
        this.latestNote = null;
        return msg;
    }

    /**
     * Gets the selling price based on the remaining oil.
     *
     * @return selling price
     */
    @Override
    public int getSellPrice() {
        return oil * PRICE_PER_OIL;
    }

    /**
     * Applies the effect after selling the lantern.
     *
     * @param seller the actor selling the item
     * @param map the current game map
     * @param wallet the seller's credit holder
     * @return selling effect description
     */
    @Override
    public String soldBy(Actor seller, GameMap map, CreditHolder wallet) {
        String result = "";

        if (random.nextInt(100) < BURN_CHANCE) {
            seller.addStatus(new BurningStatus(BURN_DURATION));
            seller.addStatus(new BurningStatus(BURN_DURATION));
            result += seller + " is burned for " + BURN_DURATION
                    + " turns, taking 2 damage per turn. ";
        }

        if (random.nextInt(100) < FIRE_CHANCE) {
            spawnFireAround(map.locationOf(seller));
            result += "Fire spreads to the surrounding tiles. ";
        }

        if (result.isEmpty()) {
            return "The lantern is sold safely.";
        }

        return result;
    }

    /**
     * Reacts to infection by adding an infection status to this item.
     *
     * @param location the location of the infected lantern
     */
    @Override
    public void reactToInfection(Location location) {
        this.addStatus(new InfectionStatus());
    }

    /**
     * Updates the infected lantern each turn.
     * Infection reduces the lantern oil by one without going below zero.
     *
     * @param location the location of the infected lantern
     */
    @Override
    public void updateInfection(Location location) {
        this.oil = Math.max(0, this.oil - 1);
    }

    /**
     * Spawns fire around a location.
     *
     * @param location the centre location
     */
    private void spawnFireAround(Location location) {
        for (Exit exit : location.getExits()) {
            Location destination = exit.getDestination();
            Ground currentGround = destination.getGround();

            FireStackable existingFire = destination.getGroundAs(FireStackable.class);
            if (existingFire != null) {
                existingFire.addStack();
            } else {
                destination.setGround(new Fire(currentGround));
            }
        }
    }

    /**
     * Returns a string representation of the lantern including its fuel level.
     *
     * @return the item name and remaining oil units
     */
    @Override
    public String toString() {
        return super.toString() + " (Oil: " + oil + ")";
    }
}