package game.capabilities;

import edu.monash.fit2099.engine.actors.Actor;
import edu.monash.fit2099.engine.positions.GameMap;
import game.managers.QuotaManager;

/**
 * Interface for items that can be deposited to the SuperComputer in exchange for company
 * credits and will trigger certain effects after depositing them.
 *
 * @author Victoria Tay Wen Xie
 * @version 1.0
 */
public interface Depositable {

    /**
     * This is to get the company credit values awarded when the
     * depositable is sold to the SuperComputer.
     * @return the number of Company Credits generated by depositing this item
     */
    public int getCompanyCreditValue();
    /**
     * Performs the deposit action for this item
     * @param actor the actor depositing the item
     * @param map the current game map
     * @param quotaManager the current quota manager
     * @return a description of the deposit result
     */
    String depositBy(Actor actor, GameMap map, QuotaManager quotaManager);
}
