package game.actions;

import edu.monash.fit2099.engine.actions.Action;
import edu.monash.fit2099.engine.actors.Actor;
import edu.monash.fit2099.engine.positions.GameMap;
import edu.monash.fit2099.engine.positions.Location;
import game.managers.QuotaManager;
import game.sanctuary.DistortionSource;
import game.utils.SpatialSearch;

/**
 * A facility action generated by the SuperComputer that performs a radius-3 scan,
 * identifies nearby distortion anomalies, and audits each one to contribute credits
 * to the QuotaManager and trigger a final unstable effect.
 *
 * @author Chathya Attanayake
 * @version 1.0
 */
public class DistortionAuditAction extends Action {

    /** The location of the SuperComputer performing the audit. */
    private final Location auditOrigin;

    /** The shared quota system — injected, not a singleton. */
    private final QuotaManager quotaManager;

    /** Radius of the spatial scan. */
    private static final int SCAN_RADIUS = 3;

    /**
     * Creates a DistortionAuditAction originating from the SuperComputer's location.
     *
     * @param auditOrigin  the SuperComputer's location on the map
     * @param quotaManager the shared quota system
     */
    public DistortionAuditAction(Location auditOrigin, QuotaManager quotaManager) {
        this.auditOrigin = auditOrigin;
        this.quotaManager = quotaManager;
    }

    /**
     * Scans a radius-3 area, audits every DistortionSource found, and reports results.
     *
     * @param actor the worker initiating the audit
     * @param map   the game map
     * @return full audit report
     */
    @Override
    public String execute(Actor actor, GameMap map) {
        StringBuilder report = new StringBuilder();
        report.append("\u001B[36m[DISTORTION AUDIT PROTOCOL INITIATED]\u001B[0m\n");
        report.append(actor).append(" initiates a corporate scan from the facility terminal.\n");

        int anomaliesFound = 0;

        // Radius-3 AoE scan using SpatialSearch
        for (Location loc : SpatialSearch.getLocationsWithinDistance(auditOrigin, SCAN_RADIUS)) {

            DistortionSource source = loc.getGroundAs(DistortionSource.class);

            if (source != null) {
                anomaliesFound++;
                report.append("\u001B[33m>>> Anomaly detected at (")
                        .append(loc.x()).append(",").append(loc.y()).append("): ")
                        .append(loc.getGround()).append("\u001B[0m\n");

                // Delegate all audit logic to the anomaly itself (SRP + LSP)
                String auditResult = source.audit(quotaManager, loc);
                report.append(auditResult).append("\n");
            }
        }

        if (anomaliesFound == 0) {
            report.append("No spatial anomalies detected within scan radius.\n");
        } else {
            report.append("\u001B[32m[AUDIT COMPLETE] ").append(anomaliesFound)
                    .append(" anomaly/anomalies processed. Credits submitted to corporate.\u001B[0m");
        }

        return report.toString();
    }

    /**
     * Returns the menu description for this action.
     *
     * @param actor the worker
     * @return menu text
     */
    @Override
    public String menuDescription(Actor actor) {
        return actor + " initiates Distortion Audit Protocol (radius " + SCAN_RADIUS + " scan)";
    }
}